### ISSUE TITLE
Prepare a Dowse RPi image snapshot system

### ISSUE THREAD

**Issue by jaromil** [dyne/dowse#19]
Using Devuan as base system

**Comment by parazyd** [comment]
For the network setup, do you have any ideas on automating the setup? Usecase for example when a user just wants to power on the device and use Dowse?

**Comment by jaromil** [comment]
Two main use cases:

 1. (default) Dowse starts up as a WIFI AP, seeking for DHCP on the ETH, assuming is WAN.
 2. (advanced) Dowse offers DHCP on ETH, then starts up as a WIFI antenna scanning for APs

In zuper there are new functions to operate some scans, they are prefixed as `net.`

**Comment by Technoprenerd** [comment]
Definitely interested this.
Since it seems I cannot make install on the latest Rasbian for RPi2.

**Comment by jaromil** [comment]
Hi Yann! To build your own image you can use our same base system which is Devuan, we have RPI1, 2 and 3 images ready here https://files.devuan.org/devuan_jessie_beta/embedded/ along with many other platforms.
If you like to chip in to support our development effort then you can also pre-order an SD image loaded with a stable version of Dowse once ready on https://www.produzionidalbasso.com/project/dowse-the-privacy-hub-for-the-internet-of-things (in the Rewards section).
Thanks for your interest!

**Comment by Technoprenerd** [comment]
@jaromil Thanks!
I've tried dd'ing the image on an microsd card, and still had not success connecting with ssh.
:') I'll keep trying to get it to work, and will look into the rewards section

**Comment by parazyd** [comment]
I am due to refresh all those images that are available for download soon. There might be bugs in some ATM. Sorry for the incovenience.

**Comment by Technoprenerd** [comment]
Okay, no problem.

The bug is that the ssh connection keeps getting reset/closed.
Not even password prompt.

**Comment by parazyd** [comment]
@Technoprenerd 
That's because the keys aren't regenerated probably. You can change /etc/rc.local on the sd card. See this: https://github.com/dyne/arm-sdk/blob/next/extra/generic-root/etc/rc.local

**Comment by Technoprenerd** [comment]
@parazyd Aha, that way. Thanks, will check and try this out.
