### ISSUE TITLE
Netdata - broken link on box

### ISSUE THREAD

**Issue by freddbomba** [dyne/dowse#26]
Broken links on netdata page on dowse box for workshops
 http://dowse.it:29999/#system_cpu;theme=slate;help=true
it goes to look for http://localhost

**Comment by parazyd** [comment]
ACK. Since webui has changed, this needs an update. Sorry for the incovenience.

**Comment by freddbomba** [comment]
noproblem!
J asked me to fill the issue on github, I think is a simple thing
I will put myself online as soon as I can tmorrow afternoon. First thing i pop on irc
ciao

f

**Comment by parazyd** [comment]
Fixed in 6c247f8998d0cf45ea5c25a5d6581dbda2cb25a3.
