### ISSUE TITLE
Setting names of other devices

### ISSUE THREAD

**Issue by tamberg** [dyne/dowse#45]
Not sure if it's a bug or a feature. The http://dowse.it/things UI allows to set a name for another device. Nice for headless devices, but might be annoying for other people in the same network? How about making it an "admin"-only feature?

**Comment by jaromil** [comment]
Considering one could change names by mistake, or usa a changed name to spoof a LAN service, I think this is a good suggestion.

**Comment by parazyd** [comment]
This was also changed with commit 9eb31f9e7da4520dfe27689103ce38979a59b72a. As for admins being able to change other names, I will attend this soon. Thanks.
